Document: dewpoint
Title: Debian dewpoint Manual
Author: <insert document author here>
Abstract: This manual describes what dewpoint is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dewpoint/dewpoint.sgml.gz

Format: postscript
Files: /usr/share/doc/dewpoint/dewpoint.ps.gz

Format: text
Files: /usr/share/doc/dewpoint/dewpoint.text.gz

Format: HTML
Index: /usr/share/doc/dewpoint/html/index.html
Files: /usr/share/doc/dewpoint/html/*.html
